### ISSUE TITLE
the pretrained model of CSPDarkNet-53 is not aviliable, please help!

### ISSUE THREAD

**Issue by h030162** [megvii-model/YOLOF#1]
https://1drv.ms/u/s!AgM0VtBH3kV9imGxZX3n_TMQGtbP?e=YMgpGJ
is not an aviliable link, and also the models' link.

**Comment by chensnathan** [comment]
Thanks for reporting that! Actually, It's a valid link. I will upload the models to `Baidu Cloud` to make them easy to access.

**Comment by chensnathan** [comment]
You can download the models [here](https://pan.baidu.com/s/1BSOncRYq6HeCQ8q2hrWowA) with code `qr6o `.

**Comment by h030162** [comment]
thanks!
