### ISSUE TITLE
unable to test

### ISSUE THREAD

**Issue by ma3252788** [megvii-model/YOLOF#12]
I noticed that there is already a cvpods directory in the project. Do I need to download cvpods again?

Do I need to delete the existing cvpods if I download it again?

How to install cvpods if I don’t need to download it? Because if I use `pip install -e cvpods --user` to install directly, it will be unavailable due to lack of setup.py.

![image](https://user-images.githubusercontent.com/22229456/112249695-2abc5980-8c93-11eb-909b-f45131e927e9.png)

**Comment by chensnathan** [comment]
You can follow the steps listed [here](https://github.com/megvii-model/YOLOF/issues/6#issuecomment-803542965).
