### ISSUE TITLE
Training on custom dataset

### ISSUE THREAD

**Issue by Zumbalamambo** [megvii-model/YOLOF#2]
How do I train on a custom dataset?

**Comment by chensnathan** [comment]
You can refer to [the tutorial](https://github.com/Megvii-BaseDetection/cvpods/pull/16/files#diff-0b84f7761834d506261c410494ab91732b9f6d7720396af2a5b3b8cfdc566ffe) in `cvpods`.

**Comment by chensnathan** [comment]
The tutorial is updated [here](https://github.com/Megvii-BaseDetection/cvpods/blob/add_tutorials/docs/tutorials/cvpods%20tutorials.ipynb). You can also check [here](https://github.com/Megvii-BaseDetection/cvpods/pull/50).
