### ISSUE TITLE
Could you explain figure 4 in your paper?

### ISSUE THREAD

**Issue by black12357** [megvii-model/YOLOF#25]
![Selection_001](https://user-images.githubusercontent.com/51944439/117415262-138baf80-af53-11eb-8442-34ba613c81e3.png)
Thank you for your great work. But I still don't understand figure 4 in your paper. (green dots stand for? 3 consecutive dots, 2 consecutive dots, 1 consecutive dot mean?)
If it's possible, please describe the figure 4.
Thank you so much!

**Comment by chensnathan** [comment]
Hi, Figure4 is just a toy example. Green dots represent the scales of objects in the image. And there are no specific means for 2 or 3 consecutive dots.
