### ISSUE TITLE
cannot import name '_C' from 'cvpods'

### ISSUE THREAD

**Issue by Huzhen757** [megvii-model/YOLOF#26]
Hello, I'm debugging the train under the tools folder 'train_net.py'.But  in the cvpods folder, on line 11 of the deform_conv script :
from cvpods import _C. report an error here:
cannot import name '_ C 'from' cvpods'

Why is this? Do I need to install any plug-ins?
Thanks！

**Comment by chensnathan** [comment]
Hi, have you followed the instructions in README and train yolof successfully?

**Comment by Huzhen757** [comment]
OK, I downloaded cvpods library yesterday and compiled it. This problem has been solved. Thank you!
