### ISSUE TITLE
How to use pretraining weights for training? 

### ISSUE THREAD

**Issue by Huzhen757** [megvii-model/YOLOF#27]
How to use pretraining weights for training? After downloading the pretraining weight, which folder should I put it in? How to call the pretraining weight file?

Thanks！

**Comment by chensnathan** [comment]
[Here](https://github.com/megvii-model/YOLOF/blob/main/playground/detection/coco/yolof/yolof.cspdarknet53.DC5.9x.stage2.3x/config.py#L6) is an example to use pre-trained weights.

**Comment by Huzhen757** [comment]
OK, I just need to change the weight address of the config file. I haven't used cvpods library. It's not very clear. Thank you very much for your answer!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "megvii-model/YOLOF"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月12日(星期三) 下午3:35
***@***.***&gt;;
抄送:&nbsp;"Hide on ***@***.******@***.***&gt;;
主题:&nbsp;Re: [megvii-model/YOLOF] How to use pretraining weights for training?  (#27)





 
Here is an example to use pre-trained weights.
