### ISSUE TITLE
What's the difference between YOLOF_CSP_D_53_DC5_9x_stage2_3x and YOLOF_CSP_D_53_DC5_9x?

### ISSUE THREAD

**Issue by developer0hye** [megvii-model/YOLOF#30]
Thanks for sharing your research!

I have one question.

What's the difference between YOLOF_CSP_D_53_DC5_9x_stage2_3x and YOLOF_CSP_D_53_DC5_9x?

**Comment by chensnathan** [comment]
Hi, we give all differences in the config file. The differences are:

1. The `NEG_IGNORE_THRESHOLD` and `POS_IGNORE_THRESHOLD` are different
2. The pre-train weights is different
3. The `LR_SCHEDULER` is different

**Comment by developer0hye** [comment]
Thanks for your reply!
What does stage2 mean?

**Comment by chensnathan** [comment]
According to the paper, when comparing YOLOF with YOLOv4, we adopt a three-stage training schedule. You can find all the details in the Appendix of the paper.

**Comment by developer0hye** [comment]
Thanks a lot!
