### ISSUE TITLE
Weight Initialization method in DilatedEncoder

### ISSUE THREAD

**Issue by developer0hye** [megvii-model/YOLOF#31]
https://github.com/megvii-model/YOLOF/blob/6189487b80601dfeda89302c22abac060f977785/playground/detection/coco/yolof/yolof_base/encoder.py#L64-L78

Why the weight initialization method for lateral_conv and fpn_conv is different from the weight initialization method for conv layer in dilated_encoder_blocks?

**Comment by chensnathan** [comment]
For `lateral_conv` and `fpn_conv`, we follow the weight initialization method in FPN. For others, we follow the weight initialization method in the head of RetinaNet.

We did not tune the methods of weight initialization. You can try other methods.

**Comment by developer0hye** [comment]
@chensnathan 
Thanks for your reply!
