### ISSUE TITLE
How do you implement the single in multiple out experiments?

### ISSUE THREAD

**Issue by freshn** [megvii-model/YOLOF#34]
Hi. In your paper, Fig 1 shows SiMo style can get competitively good results, but I am wondering about the detailed architecture during experiments. How do you generate multiple outputs with a single input? Do you pick up outputs from the deeper layers to make predictions like how SSD has done?

**Comment by chensnathan** [comment]
Hi. We provide a detailed structure for SiMo encoder in the Appendix of the paper. You can find it in Figure 8.

**Comment by freshn** [comment]
Oh cool. I didn't download the latest version of your paper. Thank you.
