### ISSUE TITLE
How to convert your moder to onnx?

### ISSUE THREAD

**Issue by nTnZone** [megvii-model/YOLOF#39]
which file can create model and so I can use torch.onnx._export to convert pth to onnx?

**Comment by nTnZone** [comment]
I also note that 'from cvpods.config import get_cfg' in plain_train_net.py, but in cvpods it dosen't exist config package, configs indeed @chensnathan

**Comment by nTnZone** [comment]
Do you have any file likes YOLOX.exp for this project to quickly config?

**Comment by ksv87** [comment]
@nTnZone you did it?
