### ISSUE TITLE
paper

### ISSUE THREAD

**Issue by abcxs** [megvii-model/YOLOF#4]
hello, the effect of large objects is a 9.3% difference, which is not small compared to others
![image](https://user-images.githubusercontent.com/13503336/111754366-e0259080-88d2-11eb-8e11-f4d18a0d3f2d.png)
![image](https://user-images.githubusercontent.com/13503336/111754383-e582db00-88d2-11eb-8f43-a899ac8b454d.png)

**Comment by chensnathan** [comment]
Thanks for your interest.

Yes. Uniform Matching has a big effect on objects across various scales when we apply it to the baseline (the first line). It makes the model be fully trained as all ground truths participate in the training phase. However, its effect on large objects diminishes when we add Dilated Encoder. Thus, we may think that Uniform Matching improves the performance of small and medium objects largely while Dilated Encoder dominates large objects' performance.

**Comment by abcxs** [comment]
thanks
