### ISSUE TITLE
How to get FLOPS and params of YOLOF?

### ISSUE THREAD

**Issue by ijrys** [megvii-model/YOLOF#46]
I don't find relevent code in YOLOF and cvpods

**Comment by ytoon** [comment]
You can find relevant code about flops in [here](https://github.com/Megvii-BaseDetection/cvpods/blob/53fd3df74dc0bda9c0718f43a293bfb1bcd34fb6/tools/analysis_net.py).  You can also use this [tools](https://github.com/open-mmlab/mmdetection/blob/master/tools/analysis_tools/get_flops.py) provided by mmdetection.
