### ISSUE TITLE
python3: can't open file '/tmp/pip-req-build-6jhijoew/tools/train_net.py

### ISSUE THREAD

**Issue by 2019ZSS** [megvii-model/YOLOF#6]
I follow the instructions and install dependencies,
cd /YOLOF/playground/detection/coco/yolof/yolof.res50.C5.1x
But when I input:
pods_train --num-gpus 2
I get a problem:
python3: can't open file '/tmp/pip-req-build-6jhijoew/tools/train_net.py': [Errno 2] No such file or directory
this what happen?

**Comment by chensnathan** [comment]
Could you provide more details about how you install `cvpods`?

**Comment by 2019ZSS** [comment]
according to https://github.com/megvii-model/YOLOF/blob/main/README_cvpods.md
just use command: pip install 'git+https://github.com/Megvii-BaseDetection/cvpods.git' --user

**Comment by chensnathan** [comment]
As we already include the `cvpods` package in this repo, you may install and run with the following steps:
```
git clone git@github.com:megvii-model/YOLOF.git
cd YOLOF/
python setup.py develop
cd ./playground/detection/coco/yolof/yolof.res50.C5.1x
pods_train --num-gpus 2
```
BTW, thanks for reporting this. Will refactor the codebase soon to avoid ambiguity.

**Comment by 2019ZSS** [comment]
Thanks for your reply.
I did as you said , but I get the same problem.
Maybe that's not the problem

**Comment by chensnathan** [comment]
If you follow the steps above, the error should not start with '/tmp/pip'. It will use the file for training whose path is `YOLOF/tools/train_net.py`. You can check that in the file `YOLOF/tools/pods_train`. 

Have you uninstalled the previously installed `cvpods` before you re-install this repo? Or are there any errors that occur during the installation?

**Comment by 2019ZSS** [comment]
I reinstall cvpods and YOLOF to solve the above problem.
But when I run:  pods_train --num-gpus 2
I get a new problem:
```python
Traceback (most recent call last):
  File "/home/stu/zss/YOLOF/tools/train_net.py", line 23, in <module>
    from cvpods.engine import RUNNERS, default_argument_parser, default_setup, hooks, launch
  File "/home/stu/zss/YOLOF/cvpods/engine/__init__.py", line 3, in <module>
    from .hooks import *
  File "/home/stu/zss/YOLOF/cvpods/engine/hooks.py", line 15, in <module>
    from cvpods.evaluation.testing import flatten_results_dict
  File "/home/stu/zss/YOLOF/cvpods/evaluation/__init__.py", line 9, in <module>
    from .lvis_evaluation import LVISEvaluator
  File "/home/stu/zss/YOLOF/cvpods/evaluation/lvis_evaluation.py", line 12, in <module>
    from lvis import LVISEval, LVISResults
ModuleNotFoundError: No module named 'lvis'
```
I try to install python-lvis module, but this is not useful.

**Comment by 2019ZSS** [comment]
soory, I shoudl pip intall lvis module, now it's work. thanks

**Comment by 2019ZSS** [comment]
Now it's ok
