### ISSUE TITLE
bash: pods_train: command not found

### ISSUE THREAD

**Issue by gpsherry** [megvii-model/YOLOF#8]
![image](https://user-images.githubusercontent.com/73693444/112086634-88836f80-8bc7-11eb-81bd-55586c756817.png)

**Comment by chensnathan** [comment]
Hi,

have you installed `cvpods`? If not, you can install it with:
```
cd YOLOF/
python setup.py develop
```

**Comment by BIT-wenzi** [comment]
作者您好，请问一下为什么我运行setup.py develop直接退出我的运行界面呢？
我的环境是torch=1.8，torchvision=0.8，python=3.8，难道是因为版本太高么？
按理说不应该啊，

**Comment by chensnathan** [comment]
@BIT-wenzi 感觉不应该直接退出运行界面啊。。退出之间有报错嘛？

**Comment by tangjiuqi097** [comment]
@BIT-wenzi 确实是torch版本太高了

**Comment by BIT-wenzi** [comment]
请问您是哪个版本使用torch1.7么？
---------- Origin message ----------
>From："wym" ***@***.***>
>To："megvii-model/YOLOF" ***@***.***>
>Subject：Re: [megvii-model/YOLOF] bash: pods_train: command not found (#8)
>Date：2021-03-25 13:27:09

@BIT-wenzi 确实是torch版本太高了

**Comment by BIT-wenzi** [comment]
主要是我安装都没成功，而且每次安装的时候直接会导致pycharm直接退出。
---------- Origin message ----------
>From："qiang chen" ***@***.***>
>To："megvii-model/YOLOF" ***@***.***>
>Subject：Re: [megvii-model/YOLOF] bash: pods_train: command not found (#8)
>Date：2021-03-24 10:38:57

@BIT-wenzi 感觉不应该直接退出运行界面啊。。退出之间有报错嘛？

**Comment by tangjiuqi097** [comment]
@BIT-wenzi  我用的是torch1.6，不过1.7应该也可以吧。你可以试试在终端编译cvpods

**Comment by BIT-wenzi** [comment]
好的，那我先试一下，感谢！
---------- Origin message ----------
>From："wym" ***@***.***>
>To："megvii-model/YOLOF" ***@***.***>
>Subject：Re: [megvii-model/YOLOF] bash: pods_train: command not found (#8)
>Date：2021-03-26 11:39:14

@BIT-wenzi  我用的是torch1.6，不过1.7应该也可以吧。你可以试试在终端编译cvpods

**Comment by poodarchu** [comment]
you can clone cvpods onto your local machine, and run pip install -e . @BIT-wenzi
